FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/Portfolio.Web/Portfolio.Web.csproj", "Portfolio.Web/"]
COPY ["src/Portfolio.Application/Portfolio.Application.csproj", "Portfolio.Application/"]
COPY ["src/Portfolio.Domain/Portfolio.Domain.csproj", "Portfolio.Domain/"]
RUN dotnet restore "Portfolio.Web/Portfolio.Web.csproj"

COPY src/ .
WORKDIR "/src/Portfolio.Web"
RUN dotnet build "Portfolio.Web.csproj" -c Release -o /app/build
RUN dotnet publish "Portfolio.Web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=build /app/publish/wwwroot .
COPY src/Portfolio.Web/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
